apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: hello
spec:
  source:
    git:
      url: "https://github.com/spara/hello.git"
      revision: master
  steps:
  - name: build-and-push
    image: "gcr.io/kaniko-project/executor:v0.6.0"
    args:
    - "--dockerfile=/workspace/app/Dockerfile"
    - "--destination=gcr.io/serverless-248400/hello"
